### ISSUE TITLE
Consider changing the highlight color of the code blocks

### ISSUE THREAD

**Issue by rednafi** [florimondmanca/www#71]
Hi, 

Your blog is awesome. As I was going through the ASGI intro, I came to notice that the syntax highlighting of the code blocks makes them hard to read. Especially the dark purple on the black background is almost illegible. Please consider changing it to something with a bit more contrast.

![Screenshot from 2020-06-02 11-35-36](https://user-images.githubusercontent.com/30027932/83484097-f722ff80-a4c5-11ea-8822-5313adae59b0.png)

![Screenshot from 2020-06-02 11-35-52](https://user-images.githubusercontent.com/30027932/83484137-07d37580-a4c6-11ea-8780-781ddf6fee44.png)

**Comment by florimondmanca** [comment]
Heya,

Thanks yup, I agree and that was in my mental backlog. Guess it’s fine to have this properly logged now. :)
